/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.practica04.formas;

import java.util.Enumeration;
import java.util.LinkedList;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import uam.pvoe.practica04.modelo.Atractivo;
import uam.pvoe.practica04.modelo.Estado;
import uam.pvoe.practica04.modelo.MedioTransporte;
import uam.pvoe.practica04.modelo.Servicio;
import uam.pvoe.practica04.operaciones.Operaciones;

/**
 *
 * @author josue
 */
public class FrmVacaciones extends javax.swing.JFrame {
    LinkedList<JCheckBox> listaChk = new LinkedList(); 
    /**
     * Creates new form FrmVacaciones
     */
    public FrmVacaciones() {
        initComponents();
        agruparSelecciones(); 
        llenarBotonesViaje(); 
        agruparCheckBoxes(); 
        llenarCheckBoxes();
        cmbEstados.removeAllItems();
        cmbAtractivos.removeAllItems();
        llenarEstados();
        ocultarTodo(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        btnGpViaje = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        cmbEstados = new javax.swing.JComboBox<>();
        cmbAtractivos = new javax.swing.JComboBox<>();
        lblSeleccionaEstado = new javax.swing.JLabel();
        lblSeleccionaAtractivo = new javax.swing.JLabel();
        lblServicioAdicional = new javax.swing.JLabel();
        spr = new javax.swing.JSeparator();
        btnAutobus = new javax.swing.JRadioButton();
        btnAvion = new javax.swing.JRadioButton();
        btnAutoPropio = new javax.swing.JRadioButton();
        btnAutoRentado = new javax.swing.JRadioButton();
        lblFormaViaje = new javax.swing.JLabel();
        chkDesayuno = new javax.swing.JCheckBox();
        chkTour = new javax.swing.JCheckBox();
        chkLavanderia = new javax.swing.JCheckBox();
        chkGuarderia = new javax.swing.JCheckBox();
        chkCajaFuerte = new javax.swing.JCheckBox();
        chkDespertador = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta para Vacaciones");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblTitulo.setText("Selección de Destinos Turísticos");

        cmbEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadosActionPerformed(evt);
            }
        });

        cmbAtractivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAtractivosActionPerformed(evt);
            }
        });

        lblSeleccionaEstado.setText("Selecciona el Estado");

        lblSeleccionaAtractivo.setText("Selecciona el Atractivo Turístico");

        lblServicioAdicional.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblServicioAdicional.setText("Servicios Adicionales en tu Estancia");

        lblFormaViaje.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFormaViaje.setText("¿Cómo piensas viajar?");

        chkDesayuno.setText("jCheckBox1");

        chkTour.setText("jCheckBox2");

        chkLavanderia.setText("jCheckBox3");

        chkGuarderia.setText("jCheckBox4");

        chkCajaFuerte.setText("jCheckBox5");

        chkDespertador.setText("jCheckBox6");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spr, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitulo)
                            .addComponent(cmbEstados, 0, 498, Short.MAX_VALUE)
                            .addComponent(cmbAtractivos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblSeleccionaEstado)
                        .addComponent(lblSeleccionaAtractivo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAutobus)
                            .addGap(64, 64, 64)
                            .addComponent(btnAvion)
                            .addGap(69, 69, 69)
                            .addComponent(btnAutoPropio)
                            .addGap(70, 70, 70)
                            .addComponent(btnAutoRentado))
                        .addComponent(lblFormaViaje)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(chkTour)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkGuarderia))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(chkDesayuno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkLavanderia))
                                .addComponent(lblServicioAdicional, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chkCajaFuerte)
                                .addComponent(chkDespertador)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addComponent(lblSeleccionaEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblSeleccionaAtractivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAtractivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(spr, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFormaViaje)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutobus)
                    .addComponent(btnAvion)
                    .addComponent(btnAutoPropio)
                    .addComponent(btnAutoRentado))
                .addGap(37, 37, 37)
                .addComponent(lblServicioAdicional)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDesayuno)
                    .addComponent(chkLavanderia)
                    .addComponent(chkCajaFuerte))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTour)
                    .addComponent(chkGuarderia)
                    .addComponent(chkDespertador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadosActionPerformed
        // TODO add your handling code here:
        mostrarAtractivos(); 
    }//GEN-LAST:event_cmbEstadosActionPerformed

    private void cmbAtractivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAtractivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAtractivosActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        System.out.println("------------------------------- REGISTRO COMPLETADO ---------------------------");
        Estado estado = (Estado) cmbEstados.getSelectedItem();
        System.out.println("CLAVE ESTADO: " + estado.getClave());
        Atractivo atractivo = (Atractivo) cmbAtractivos.getSelectedItem(); 
        System.out.println("CLAVE ATRACTIVO: " + atractivo.getAtractivo());
        
        //verificamos el tipo de transporte 
        Enumeration<AbstractButton> btnGrp = btnGpViaje.getElements(); 
        while(btnGrp.hasMoreElements()){
            JRadioButton btnAux = (JRadioButton) btnGrp.nextElement(); 
            if(btnAux.isSelected()){
                MedioTransporte medio = (MedioTransporte) btnAux.getClientProperty("key"); 
                System.out.println("CLAVE DE MEDIO DE TRANSPORTE: " + medio.getClave());
            }
        }
        
        //verificamos los servicios 
        System.out.println("CLAVE DE SERVICIOS INCLUIDOS: ");
        int cont = 0; 
        for(JCheckBox aux : listaChk){
            if(aux.isSelected()){
                Servicio servicio = (Servicio) aux.getClientProperty("llave");
                System.out.println(servicio.getClave());
                cont++; 
            }
        }
        if(cont == 0){
            System.out.println("NO INCLUYO SERVICIOS");
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    public void mostrarAtractivos(){
        Estado estado = (Estado) cmbEstados.getSelectedItem(); 
        int indice = cmbEstados.getSelectedIndex(); 
        
        if(indice != 0){
            cmbAtractivos.removeAllItems();
            llenarAtractivos(estado.getClave());
            mostrarTodo(); 
            
        }else{
            ocultarTodo();
        }
    }
    
    
    
    public void ocultarTodo(){
        cmbAtractivos.setVisible(false);
        lblSeleccionaAtractivo.setVisible(false);
        lblSeleccionaEstado.setVisible(false);
        lblServicioAdicional.setVisible(false); 
        spr.setVisible(false);
        btnAutoPropio.setVisible(false);
        btnAvion.setVisible(false);
        btnAutoRentado.setVisible(false);
        btnAutobus.setVisible(false);
        btnRegistrar.setVisible(false);
        lblFormaViaje.setVisible(false); 
        chkCajaFuerte.setVisible(false);
        chkDesayuno.setVisible(false);
        chkDespertador.setVisible(false);
        chkGuarderia.setVisible(false);
        chkLavanderia.setVisible(false);
        chkTour.setVisible(false);
        limpiarChk();
       
    }
    
    public void limpiarChk(){
        chkCajaFuerte.setSelected(false); 
        chkDesayuno.setSelected(false); 
        chkDespertador.setSelected(false); 
        chkGuarderia.setSelected(false); 
        chkLavanderia.setSelected(false); 
        chkTour.setSelected(false); 
    }
    
    public void mostrarTodo(){
        cmbAtractivos.setVisible(true);
        lblSeleccionaAtractivo.setVisible(true);
        lblSeleccionaEstado.setVisible(true);
        lblServicioAdicional.setVisible(true); 
        spr.setVisible(true);
        btnAutoPropio.setVisible(true);
        btnAvion.setVisible(true);
        btnAutoRentado.setVisible(true);
        btnAutobus.setVisible(true);
        btnRegistrar.setVisible(true);
        lblFormaViaje.setVisible(true); 
        chkCajaFuerte.setVisible(true);
        chkDesayuno.setVisible(true);
        chkDespertador.setVisible(true);
        chkGuarderia.setVisible(true);
        chkLavanderia.setVisible(true);
        chkTour.setVisible(true);
    }
    
    public void llenarBotonesViaje(){
        MedioTransporte medio1 = new MedioTransporte(); 
        MedioTransporte medio2 = new MedioTransporte(); 
        MedioTransporte medio3 = new MedioTransporte(); 
        MedioTransporte medio4 = new MedioTransporte(); 
        
        medio1.setNombre("Auto");
        medio1.setClave("AUTO");
        medio2.setNombre("Autobús");
        medio2.setClave("BUS");
        medio3.setNombre("Avión");
        medio3.setClave("AVION");
        medio4.setNombre("Auto rentado");
        medio4.setClave("AUTO_R");
        
        btnAutoPropio.setText(medio1.getNombre());
        btnAutobus.setText(medio2.getNombre());
        btnAvion.setText(medio3.getNombre());
        btnAutoRentado.setText(medio4.getNombre());
        
        btnAutoPropio.putClientProperty("key", medio1); 
        btnAutobus.putClientProperty("key", medio2); 
        btnAvion.putClientProperty("key", medio3); 
        btnAutoRentado.putClientProperty("key", medio4);
        
        btnAutoPropio.setSelected(true); 
        
    }
    
    public void llenarCheckBoxes(){
             /*Los nombres serán:
    
                Desayuno
                Recorridos
                Lavandería
                Guardería
                Caja Fuerte
                Despertador
                */

                 /* Las claves serán:

                DES
                REC
                LAV
                GUAR
                CAJA
                DESP
                */
                 
                 
        Servicio desayuno = new Servicio(); 
        Servicio recorridos = new Servicio(); 
        Servicio lavanderia = new Servicio(); 
        Servicio guarderia = new Servicio(); 
        Servicio caja = new Servicio(); 
        Servicio despertador = new Servicio();
        
        
        desayuno.setNombre("Desayuno");
        desayuno.setClave("DES");
        recorridos.setNombre("Recorridos");
        recorridos.setClave("REC");
        lavanderia.setNombre("Lavanderia");
        lavanderia.setClave("LAV");
        guarderia.setNombre("Guarderia");
        guarderia.setClave("GUAR");
        caja.setNombre("Caja fuerte");
        caja.setClave("CAJA");
        despertador.setNombre("Despertador");
        despertador.setClave("DESP");
        
        
        chkDesayuno.setText(desayuno.getNombre());
        chkTour.setText(recorridos.getNombre());
        chkGuarderia.setText(lavanderia.getNombre());
        chkLavanderia.setText(guarderia.getNombre());
        chkCajaFuerte.setText(caja.getNombre());
        chkDespertador.setText(despertador.getNombre());
        
        chkDesayuno.putClientProperty("llave", desayuno); 
        chkTour.putClientProperty("llave", recorridos); 
        chkGuarderia.putClientProperty("llave", guarderia); 
        chkLavanderia.putClientProperty("llave", lavanderia); 
        chkCajaFuerte.putClientProperty("llave", caja); 
        chkDespertador.putClientProperty("llave", despertador); 
        
        

              
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVacaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVacaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVacaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVacaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVacaciones().setVisible(true);
            }
        });
    }

    public void llenarEstados(){
        Operaciones operaciones = new Operaciones(); 
        LinkedList<Estado> estados = operaciones.llenarListaEstados(); 
        for(Estado estado : estados){
            cmbEstados.addItem(estado);
        }
        
    }
    
    public void llenarAtractivos(String claveEdo){
        Operaciones operaciones = new Operaciones(); 
        LinkedList<Atractivo> atractivos = operaciones.llenarListaAtractivos(claveEdo); 
        for(Atractivo atractivo : atractivos){
            cmbAtractivos.addItem(atractivo);
        }
    }
    
    //Agrupa los radio buttons 
    public void agruparSelecciones(){
        btnGpViaje.add(btnAvion);
        btnGpViaje.add(btnAutoRentado);
        btnGpViaje.add(btnAutobus);
        btnGpViaje.add(btnAutoPropio);
    }
    
    
    //Agrupa los check boxes
    public void agruparCheckBoxes(){
        listaChk.add(chkTour); 
        listaChk.add(chkCajaFuerte); 
        listaChk.add(chkDesayuno); 
        listaChk.add(chkDespertador); 
        listaChk.add(chkGuarderia); 
        listaChk.add(chkLavanderia); 
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAutoPropio;
    private javax.swing.JRadioButton btnAutoRentado;
    private javax.swing.JRadioButton btnAutobus;
    private javax.swing.JRadioButton btnAvion;
    private javax.swing.ButtonGroup btnGpViaje;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkCajaFuerte;
    private javax.swing.JCheckBox chkDesayuno;
    private javax.swing.JCheckBox chkDespertador;
    private javax.swing.JCheckBox chkGuarderia;
    private javax.swing.JCheckBox chkLavanderia;
    private javax.swing.JCheckBox chkTour;
    private javax.swing.JComboBox<Atractivo> cmbAtractivos;
    private javax.swing.JComboBox<Estado> cmbEstados;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblFormaViaje;
    private javax.swing.JLabel lblSeleccionaAtractivo;
    private javax.swing.JLabel lblSeleccionaEstado;
    private javax.swing.JLabel lblServicioAdicional;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSeparator spr;
    // End of variables declaration//GEN-END:variables
}
